### ISSUE TITLE
Error in the console when I launch Sublime

### ISSUE THREAD

**Issue by guitaristtom** [braver/SublimeSass#73]
When I launch in to Sublime Text 3 (3211) and check the console I get an error from this package:
```
reloading plugin Sass.sass_completions
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/home/thomas/.config/sublime-text-3/Installed Packages/Sass.sublime-package/sass_completions.py", line 688
    details = f"<code>{prop}</code> property-value"
                                                  ^
SyntaxError: invalid syntax
```

**Comment by suiyuex** [comment]
I also got the same error， i guess this is python version compatible issue， any solution ?

**Comment by braver** [comment]
Damn, a python 3.8 language feature slipped in. Thanks for reporting!
